on:
  push:
     branches:
       - main

  

name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown","readr"))'
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
      - uses: actions/upload-artifact@v4
        with:
          name: _book
          path: _book/
  
# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for a GH_PAT and EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: bookdown
   steps:
     - name: Checkout
       uses: actions/checkout@v4
       with: 
          fetch-depth: 0 # fetch full history
          persist-credentials: true # so GITHUB_TOKEN is available
     - name: Download artifact
       uses: actions/download-artifact@v4
       with:
         # Artifact name
         name: book_site # optional
         # Destination path
         path: _book # optional
     - name: Deploy to GitHub Pages
       uses: peaceiris/actions-gh-pages@v3
       with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _book
          destination_dir: ""  
          user_name: "github-actions[bot]"
          user_email: yanmin@stanford.edu            # must be a verified email
          build_dir: _book/                     # "_site/" by default
          branch: gh-pages

 

